/**
 * @flow
 */

export default {
  DIRECTORY_ALREADY_EXISTS: 'DIRECTORY_ALREADY_EXISTS',
  INVALID_ARGUMENT: 'INVALID_ARGUMENT',
  INVALID_ASSETS: 'INVALID_ASSETS',
  INVALID_BUNDLE: 'INVALID_BUNDLE',
  INVALID_MANIFEST: 'INVALID_MANIFEST',
  INVALID_OPTIONS: 'INVALID_OPTIONS',
  NGROK_ERROR: 'NGROK_ERROR',
  NO_EXPONENT_SERVER_PORT: 'NO_EXPONENT_SERVER_PORT',
  NO_PACKAGE_JSON: 'NO_PACKAGE_JSON',
  NO_PACKAGER_PORT: 'NO_PACKAGER_PORT',
  NO_PORT_FOUND: 'NO_PORT_FOUND',
  NO_PROJECT_ROOT: 'NO_PROJECT_ROOT',
  NO_SDK_VERSION: 'NO_SDK_VERSION',
  NOT_LOGGED_IN: 'NOT_LOGGED_IN',
  PLATFORM_NOT_SUPPORTED: 'PLATFORM_NOT_SUPPORTED',
  WONT_OVERWRITE_WITHOUT_FORCE: 'WONT_OVERWRITE_WITHOUT_FORCE',

  //Shell Apps
  CREDENTIAL_ERROR: 'CREDENTIAL_ERROR',
};
