'use strict';

module.exports = {
  INVALID_ARGUMENT: 'INVALID_ARGUMENT',
  INVALID_BUNDLE: 'INVALID_BUNDLE',
  INVALID_OPTIONS: 'INVALID_OPTIONS',
  NO_EXPONENT_SERVER_PORT: 'NO_EXPONENT_SERVER_PORT',
  NO_PACKAGE_JSON: 'NO_PACKAGE_JSON',
  NO_PACKAGER_PORT: 'NO_PACKAGER_PORT',
  NO_PORT_FOUND: 'NO_PORT_FOUND',
  NO_PROJECT_ROOT: 'NO_PROJECT_ROOT',
  NOT_LOGGED_IN: 'NOT_LOGGED_IN',
  WONT_OVERWRITE_WITHOUT_FORCE: 'WONT_OVERWRITE_WITHOUT_FORCE',
};
