/**
 * @flow
 */

export default {
  OLD_IOS_APP_VERSION: 'OLD_IOS_APP_VERSION',
  OLD_ANDROID_APP_VERSION: 'OLD_ANDROID_APP_VERSION',
  START_LOADING: 'START_LOADING',
  STOP_LOADING: 'STOP_LOADING',
  PROGRESS: 'PROGRESS',
};
