codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  round: up
  precision: 2
  range: '30...100'

  status:
    changes: no
    patch: yes
    project:
      default:
        target: auto
        # Disable errors failing PRs when the coverage is too low
        threshold: null

comment:
  behavior: default
  require_changes: false
  layout: 'header, flags, diff'
