// flow-typed signature: 274e10b289f897429686a5fa01312b11
// flow-typed version: <<STUB>>/auth0_v^2.5.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'auth0'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'auth0' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'auth0/src/auth/DatabaseAuthenticator' {
  declare module.exports: any;
}

declare module 'auth0/src/auth/index' {
  declare module.exports: any;
}

declare module 'auth0/src/auth/OAuthAuthenticator' {
  declare module.exports: any;
}

declare module 'auth0/src/auth/PasswordlessAuthenticator' {
  declare module.exports: any;
}

declare module 'auth0/src/auth/TokensManager' {
  declare module.exports: any;
}

declare module 'auth0/src/auth/UsersManager' {
  declare module.exports: any;
}

declare module 'auth0/src/exceptions/ApiError' {
  declare module.exports: any;
}

declare module 'auth0/src/exceptions/ArgumentError' {
  declare module.exports: any;
}

declare module 'auth0/src/exceptions/index' {
  declare module.exports: any;
}

declare module 'auth0/src/index' {
  declare module.exports: any;
}

declare module 'auth0/src/management/BlacklistedTokensManager' {
  declare module.exports: any;
}

declare module 'auth0/src/management/ClientsManager' {
  declare module.exports: any;
}

declare module 'auth0/src/management/ConnectionsManager' {
  declare module.exports: any;
}

declare module 'auth0/src/management/DeviceCredentialsManager' {
  declare module.exports: any;
}

declare module 'auth0/src/management/EmailProviderManager' {
  declare module.exports: any;
}

declare module 'auth0/src/management/index' {
  declare module.exports: any;
}

declare module 'auth0/src/management/JobsManager' {
  declare module.exports: any;
}

declare module 'auth0/src/management/LogsManager' {
  declare module.exports: any;
}

declare module 'auth0/src/management/RulesManager' {
  declare module.exports: any;
}

declare module 'auth0/src/management/StatsManager' {
  declare module.exports: any;
}

declare module 'auth0/src/management/TenantManager' {
  declare module.exports: any;
}

declare module 'auth0/src/management/TicketsManager' {
  declare module.exports: any;
}

declare module 'auth0/src/management/UsersManager' {
  declare module.exports: any;
}

declare module 'auth0/src/utils' {
  declare module.exports: any;
}

declare module 'auth0/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'auth0/src/auth/DatabaseAuthenticator.js' {
  declare module.exports: $Exports<'auth0/src/auth/DatabaseAuthenticator'>;
}
declare module 'auth0/src/auth/index.js' {
  declare module.exports: $Exports<'auth0/src/auth/index'>;
}
declare module 'auth0/src/auth/OAuthAuthenticator.js' {
  declare module.exports: $Exports<'auth0/src/auth/OAuthAuthenticator'>;
}
declare module 'auth0/src/auth/PasswordlessAuthenticator.js' {
  declare module.exports: $Exports<'auth0/src/auth/PasswordlessAuthenticator'>;
}
declare module 'auth0/src/auth/TokensManager.js' {
  declare module.exports: $Exports<'auth0/src/auth/TokensManager'>;
}
declare module 'auth0/src/auth/UsersManager.js' {
  declare module.exports: $Exports<'auth0/src/auth/UsersManager'>;
}
declare module 'auth0/src/exceptions/ApiError.js' {
  declare module.exports: $Exports<'auth0/src/exceptions/ApiError'>;
}
declare module 'auth0/src/exceptions/ArgumentError.js' {
  declare module.exports: $Exports<'auth0/src/exceptions/ArgumentError'>;
}
declare module 'auth0/src/exceptions/index.js' {
  declare module.exports: $Exports<'auth0/src/exceptions/index'>;
}
declare module 'auth0/src/index.js' {
  declare module.exports: $Exports<'auth0/src/index'>;
}
declare module 'auth0/src/management/BlacklistedTokensManager.js' {
  declare module.exports: $Exports<'auth0/src/management/BlacklistedTokensManager'>;
}
declare module 'auth0/src/management/ClientsManager.js' {
  declare module.exports: $Exports<'auth0/src/management/ClientsManager'>;
}
declare module 'auth0/src/management/ConnectionsManager.js' {
  declare module.exports: $Exports<'auth0/src/management/ConnectionsManager'>;
}
declare module 'auth0/src/management/DeviceCredentialsManager.js' {
  declare module.exports: $Exports<'auth0/src/management/DeviceCredentialsManager'>;
}
declare module 'auth0/src/management/EmailProviderManager.js' {
  declare module.exports: $Exports<'auth0/src/management/EmailProviderManager'>;
}
declare module 'auth0/src/management/index.js' {
  declare module.exports: $Exports<'auth0/src/management/index'>;
}
declare module 'auth0/src/management/JobsManager.js' {
  declare module.exports: $Exports<'auth0/src/management/JobsManager'>;
}
declare module 'auth0/src/management/LogsManager.js' {
  declare module.exports: $Exports<'auth0/src/management/LogsManager'>;
}
declare module 'auth0/src/management/RulesManager.js' {
  declare module.exports: $Exports<'auth0/src/management/RulesManager'>;
}
declare module 'auth0/src/management/StatsManager.js' {
  declare module.exports: $Exports<'auth0/src/management/StatsManager'>;
}
declare module 'auth0/src/management/TenantManager.js' {
  declare module.exports: $Exports<'auth0/src/management/TenantManager'>;
}
declare module 'auth0/src/management/TicketsManager.js' {
  declare module.exports: $Exports<'auth0/src/management/TicketsManager'>;
}
declare module 'auth0/src/management/UsersManager.js' {
  declare module.exports: $Exports<'auth0/src/management/UsersManager'>;
}
declare module 'auth0/src/utils.js' {
  declare module.exports: $Exports<'auth0/src/utils'>;
}
declare module 'auth0/webpack.config.js' {
  declare module.exports: $Exports<'auth0/webpack.config'>;
}
