// flow-typed signature: 4dda624389e3303295eb6e807a00ccf9
// flow-typed version: <<STUB>>/exec-async_v^2.2.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'exec-async'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'exec-async' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'exec-async/index' {
  declare module.exports: $Exports<'exec-async'>;
}
declare module 'exec-async/index.js' {
  declare module.exports: $Exports<'exec-async'>;
}
