// flow-typed signature: 435ba3e8888c132591aecf305381fdb5
// flow-typed version: <<STUB>>/gulp-shell_v^0.5.2/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-shell'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-shell' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-shell/gulpfile' {
  declare module.exports: any;
}

declare module 'gulp-shell/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-shell/gulpfile.js' {
  declare module.exports: $Exports<'gulp-shell/gulpfile'>;
}
declare module 'gulp-shell/index' {
  declare module.exports: $Exports<'gulp-shell'>;
}
declare module 'gulp-shell/index.js' {
  declare module.exports: $Exports<'gulp-shell'>;
}
declare module 'gulp-shell/test/index.js' {
  declare module.exports: $Exports<'gulp-shell/test/index'>;
}
