// flow-typed signature: 94a86783f8033b290ee9903d6be09c4e
// flow-typed version: <<STUB>>/jsonwebtoken_v^7.2.1/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsonwebtoken'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsonwebtoken' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsonwebtoken/decode' {
  declare module.exports: any;
}

declare module 'jsonwebtoken/lib/JsonWebTokenError' {
  declare module.exports: any;
}

declare module 'jsonwebtoken/lib/NotBeforeError' {
  declare module.exports: any;
}

declare module 'jsonwebtoken/lib/timespan' {
  declare module.exports: any;
}

declare module 'jsonwebtoken/lib/TokenExpiredError' {
  declare module.exports: any;
}

declare module 'jsonwebtoken/sign' {
  declare module.exports: any;
}

declare module 'jsonwebtoken/test/async_sign.tests' {
  declare module.exports: any;
}

declare module 'jsonwebtoken/test/buffer.tests' {
  declare module.exports: any;
}

declare module 'jsonwebtoken/test/encoding.tests' {
  declare module.exports: any;
}

declare module 'jsonwebtoken/test/expires_format.tests' {
  declare module.exports: any;
}

declare module 'jsonwebtoken/test/iat.tests' {
  declare module.exports: any;
}

declare module 'jsonwebtoken/test/invalid_exp.tests' {
  declare module.exports: any;
}

declare module 'jsonwebtoken/test/issue_147.tests' {
  declare module.exports: any;
}

declare module 'jsonwebtoken/test/issue_196.tests' {
  declare module.exports: any;
}

declare module 'jsonwebtoken/test/issue_70.tests' {
  declare module.exports: any;
}

declare module 'jsonwebtoken/test/jwt.hs.tests' {
  declare module.exports: any;
}

declare module 'jsonwebtoken/test/jwt.rs.tests' {
  declare module.exports: any;
}

declare module 'jsonwebtoken/test/keyid.tests' {
  declare module.exports: any;
}

declare module 'jsonwebtoken/test/non_object_values.tests' {
  declare module.exports: any;
}

declare module 'jsonwebtoken/test/noTimestamp.tests' {
  declare module.exports: any;
}

declare module 'jsonwebtoken/test/rsa-public-key.tests' {
  declare module.exports: any;
}

declare module 'jsonwebtoken/test/set_headers.tests' {
  declare module.exports: any;
}

declare module 'jsonwebtoken/test/undefined_secretOrPublickey.tests' {
  declare module.exports: any;
}

declare module 'jsonwebtoken/test/util/fakeDate' {
  declare module.exports: any;
}

declare module 'jsonwebtoken/test/verify.tests' {
  declare module.exports: any;
}

declare module 'jsonwebtoken/test/wrong_alg.tests' {
  declare module.exports: any;
}

declare module 'jsonwebtoken/verify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsonwebtoken/decode.js' {
  declare module.exports: $Exports<'jsonwebtoken/decode'>;
}
declare module 'jsonwebtoken/index' {
  declare module.exports: $Exports<'jsonwebtoken'>;
}
declare module 'jsonwebtoken/index.js' {
  declare module.exports: $Exports<'jsonwebtoken'>;
}
declare module 'jsonwebtoken/lib/JsonWebTokenError.js' {
  declare module.exports: $Exports<'jsonwebtoken/lib/JsonWebTokenError'>;
}
declare module 'jsonwebtoken/lib/NotBeforeError.js' {
  declare module.exports: $Exports<'jsonwebtoken/lib/NotBeforeError'>;
}
declare module 'jsonwebtoken/lib/timespan.js' {
  declare module.exports: $Exports<'jsonwebtoken/lib/timespan'>;
}
declare module 'jsonwebtoken/lib/TokenExpiredError.js' {
  declare module.exports: $Exports<'jsonwebtoken/lib/TokenExpiredError'>;
}
declare module 'jsonwebtoken/sign.js' {
  declare module.exports: $Exports<'jsonwebtoken/sign'>;
}
declare module 'jsonwebtoken/test/async_sign.tests.js' {
  declare module.exports: $Exports<'jsonwebtoken/test/async_sign.tests'>;
}
declare module 'jsonwebtoken/test/buffer.tests.js' {
  declare module.exports: $Exports<'jsonwebtoken/test/buffer.tests'>;
}
declare module 'jsonwebtoken/test/encoding.tests.js' {
  declare module.exports: $Exports<'jsonwebtoken/test/encoding.tests'>;
}
declare module 'jsonwebtoken/test/expires_format.tests.js' {
  declare module.exports: $Exports<'jsonwebtoken/test/expires_format.tests'>;
}
declare module 'jsonwebtoken/test/iat.tests.js' {
  declare module.exports: $Exports<'jsonwebtoken/test/iat.tests'>;
}
declare module 'jsonwebtoken/test/invalid_exp.tests.js' {
  declare module.exports: $Exports<'jsonwebtoken/test/invalid_exp.tests'>;
}
declare module 'jsonwebtoken/test/issue_147.tests.js' {
  declare module.exports: $Exports<'jsonwebtoken/test/issue_147.tests'>;
}
declare module 'jsonwebtoken/test/issue_196.tests.js' {
  declare module.exports: $Exports<'jsonwebtoken/test/issue_196.tests'>;
}
declare module 'jsonwebtoken/test/issue_70.tests.js' {
  declare module.exports: $Exports<'jsonwebtoken/test/issue_70.tests'>;
}
declare module 'jsonwebtoken/test/jwt.hs.tests.js' {
  declare module.exports: $Exports<'jsonwebtoken/test/jwt.hs.tests'>;
}
declare module 'jsonwebtoken/test/jwt.rs.tests.js' {
  declare module.exports: $Exports<'jsonwebtoken/test/jwt.rs.tests'>;
}
declare module 'jsonwebtoken/test/keyid.tests.js' {
  declare module.exports: $Exports<'jsonwebtoken/test/keyid.tests'>;
}
declare module 'jsonwebtoken/test/non_object_values.tests.js' {
  declare module.exports: $Exports<'jsonwebtoken/test/non_object_values.tests'>;
}
declare module 'jsonwebtoken/test/noTimestamp.tests.js' {
  declare module.exports: $Exports<'jsonwebtoken/test/noTimestamp.tests'>;
}
declare module 'jsonwebtoken/test/rsa-public-key.tests.js' {
  declare module.exports: $Exports<'jsonwebtoken/test/rsa-public-key.tests'>;
}
declare module 'jsonwebtoken/test/set_headers.tests.js' {
  declare module.exports: $Exports<'jsonwebtoken/test/set_headers.tests'>;
}
declare module 'jsonwebtoken/test/undefined_secretOrPublickey.tests.js' {
  declare module.exports: $Exports<'jsonwebtoken/test/undefined_secretOrPublickey.tests'>;
}
declare module 'jsonwebtoken/test/util/fakeDate.js' {
  declare module.exports: $Exports<'jsonwebtoken/test/util/fakeDate'>;
}
declare module 'jsonwebtoken/test/verify.tests.js' {
  declare module.exports: $Exports<'jsonwebtoken/test/verify.tests'>;
}
declare module 'jsonwebtoken/test/wrong_alg.tests.js' {
  declare module.exports: $Exports<'jsonwebtoken/test/wrong_alg.tests'>;
}
declare module 'jsonwebtoken/verify.js' {
  declare module.exports: $Exports<'jsonwebtoken/verify'>;
}
