// flow-typed signature: f39fe95c49cadfed76204b011ff03560
// flow-typed version: <<STUB>>/promise-props_v^1.0.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'promise-props'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'promise-props' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'promise-props/__tests__/index-test' {
  declare module.exports: any;
}

declare module 'promise-props/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'promise-props/__tests__/index-test.js' {
  declare module.exports: $Exports<'promise-props/__tests__/index-test'>;
}
declare module 'promise-props/index' {
  declare module.exports: $Exports<'promise-props'>;
}
declare module 'promise-props/index.js' {
  declare module.exports: $Exports<'promise-props'>;
}
declare module 'promise-props/test.js' {
  declare module.exports: $Exports<'promise-props/test'>;
}
