// flow-typed signature: a2df3c568fc3e10e537b23c042e0b669
// flow-typed version: <<STUB>>/xhr2_v^0.1.3/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xhr2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'xhr2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xhr2/lib/browser' {
  declare module.exports: any;
}

declare module 'xhr2/lib/xhr2' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xhr2/lib/browser.js' {
  declare module.exports: $Exports<'xhr2/lib/browser'>;
}
declare module 'xhr2/lib/xhr2.js' {
  declare module.exports: $Exports<'xhr2/lib/xhr2'>;
}
