// flow-typed signature: 7dfe019dfeaf02ade3315034f1f82346
// flow-typed version: <<STUB>>/@exponent/osascript_v^1.6.4/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@exponent/osascript'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@exponent/osascript' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@exponent/osascript/lib/index' {
  declare module.exports: any;
}

declare module '@exponent/osascript/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@exponent/osascript/lib/index.js' {
  declare module.exports: $Exports<'@exponent/osascript/lib/index'>;
}
declare module '@exponent/osascript/src/index.js' {
  declare module.exports: $Exports<'@exponent/osascript/src/index'>;
}
