export default {
  keywords: { input: 'name', key: 'keywords', content: 'your, tags' },
  description: { input: 'name', key: 'description', content: '150 words' },
  subject: { input: 'name', key: 'subject', content: "your website's subject" },
  copyright: { input: 'name', key: 'copyright', content: 'company name' },
  language: { input: 'name', key: 'language', content: 'ES' },
  robots: { input: 'name', key: 'robots', content: 'index,follow' },
  revised: { input: 'name', key: 'revised', content: 'Sunday, July 18th, 2010, 5:15 pm' },
  abstract: { input: 'name', key: 'abstract', content: '' },
  topic: { input: 'name', key: 'topic', content: '' },
  summary: { input: 'name', key: 'summary', content: '' },
  Classification: { input: 'name', key: 'Classification', content: 'Business' },
  author: { input: 'name', key: 'author', content: 'name, email@hotmail.com' },
  designer: { input: 'name', key: 'designer', content: '' },
  'reply-to': { input: 'name', key: 'reply-to', content: 'email@hotmail.com' },
  owner: { input: 'name', key: 'owner', content: '' },
  url: { input: 'name', key: 'url', content: 'http://www.websiteaddrress.com' },
  'identifier-URL': {
    input: 'name',
    key: 'identifier-URL',
    content: 'http://www.websiteaddress.com',
  },
  directory: { input: 'name', key: 'directory', content: 'submission' },
  pagename: {
    input: 'name',
    key: 'pagename',
    content: "jQuery Tools, Tutorials and Resources - O'Reilly Media",
  },
  category: { input: 'name', key: 'category', content: '' },
  coverage: { input: 'name', key: 'coverage', content: 'Worldwide' },
  distribution: { input: 'name', key: 'distribution', content: 'Global' },
  rating: { input: 'name', key: 'rating', content: 'General' },
  'revisit-after': { input: 'name', key: 'revisit-after', content: '7 days' },
  subtitle: { input: 'name', key: 'subtitle', content: 'This is my subtitle' },
  target: { input: 'name', key: 'target', content: 'all' },
  HandheldFriendly: { input: 'name', key: 'HandheldFriendly', content: 'True' },
  MobileOptimized: { input: 'name', key: 'MobileOptimized', content: '320' },
  date: { input: 'name', key: 'date', content: 'Sep. 27, 2010' },
  search_date: { input: 'name', key: 'search_date', content: '2010-09-27' },
  'DC.title': { input: 'name', key: 'DC.title', content: 'Unstoppable Robot Ninja' },
  ResourceLoaderDynamicStyles: { input: 'name', key: 'ResourceLoaderDynamicStyles', content: '' },
  medium: { input: 'name', key: 'medium', content: 'blog' },
  'syndication-source': {
    input: 'name',
    key: 'syndication-source',
    content: 'https://mashable.com/2008/12/24/free-brand-monitoring-tools/',
  },
  'original-source': {
    input: 'name',
    key: 'original-source',
    content: 'https://mashable.com/2008/12/24/free-brand-monitoring-tools/',
  },
  'verify-v1': {
    input: 'name',
    key: 'verify-v1',
    content: 'dV1r/ZJJdDEI++fKJ6iDEl6o+TMNtSu0kv18ONeqM0I=',
  },
  y_key: { input: 'name', key: 'y_key', content: '1e39c508e0d87750' },
  pageKey: { input: 'name', key: 'pageKey', content: 'guest-home' },
  name: { input: 'itemprop', key: 'name', content: 'jQTouch' },
  Expires: { input: 'http-equiv', key: 'Expires', content: '0' },
  Pragma: { input: 'http-equiv', key: 'Pragma', content: 'no-cache' },
  'Cache-Control': { input: 'http-equiv', key: 'Cache-Control', content: 'no-cache' },
  imagetoolbar: { input: 'http-equiv', key: 'imagetoolbar', content: 'no' },
  'x-dns-prefetch-control': { input: 'http-equiv', key: 'x-dns-prefetch-control', content: 'off' },
};
