#!/bin/bash

if [ -f ~/.exponent/bashrc ]; then
   source ~/.exponent/bashrc > /dev/null
else
   if [ -f /etc/bash.bashrc ]; then
      source /etc/bash.bashrc > /dev/null
   fi

   if [ -f ~/.bashrc ]; then
      source ~/.bashrc > /dev/null
   fi
fi

echo $PATH
