// flow-typed signature: 52ace49ecf18c59e6a688dbd2c35803f
// flow-typed version: <<STUB>>/analytics-node_v^2.1.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'analytics-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'analytics-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'analytics-node/analytics-node' {
  declare module.exports: any;
}

declare module 'analytics-node/lib/index' {
  declare module.exports: any;
}

declare module 'analytics-node/test/index' {
  declare module.exports: any;
}

declare module 'analytics-node/test/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'analytics-node/analytics-node.js' {
  declare module.exports: $Exports<'analytics-node/analytics-node'>;
}
declare module 'analytics-node/lib/index.js' {
  declare module.exports: $Exports<'analytics-node/lib/index'>;
}
declare module 'analytics-node/test/index.js' {
  declare module.exports: $Exports<'analytics-node/test/index'>;
}
declare module 'analytics-node/test/server.js' {
  declare module.exports: $Exports<'analytics-node/test/server'>;
}
