// flow-typed signature: 3bf0e8580b04859df1aa82219925b9f5
// flow-typed version: <<STUB>>/auth0-js_v^7.4.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'auth0-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'auth0-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'auth0-js/Gruntfile' {
  declare module.exports: any;
}

declare module 'auth0-js/lib/assert_required' {
  declare module.exports: any;
}

declare module 'auth0-js/lib/base64_url' {
  declare module.exports: any;
}

declare module 'auth0-js/lib/IframeHandler' {
  declare module.exports: any;
}

declare module 'auth0-js/lib/index-of' {
  declare module.exports: any;
}

declare module 'auth0-js/lib/is-array' {
  declare module.exports: any;
}

declare module 'auth0-js/lib/json-parse' {
  declare module.exports: any;
}

declare module 'auth0-js/lib/LoginError' {
  declare module.exports: any;
}

declare module 'auth0-js/lib/nonce-generator' {
  declare module.exports: any;
}

declare module 'auth0-js/lib/same-origin' {
  declare module.exports: any;
}

declare module 'auth0-js/lib/SilentAuthenticationHandler' {
  declare module.exports: any;
}

declare module 'auth0-js/lib/use_jsonp' {
  declare module.exports: any;
}

declare module 'auth0-js/standalone' {
  declare module.exports: any;
}

declare module 'auth0-js/test/iframe-handler.test' {
  declare module.exports: any;
}

declare module 'auth0-js/test/index.tests' {
  declare module.exports: any;
}

declare module 'auth0-js/test/logout.tests' {
  declare module.exports: any;
}

declare module 'auth0-js/test/passwordless.tests' {
  declare module.exports: any;
}

declare module 'auth0-js/test/support/config' {
  declare module.exports: any;
}

declare module 'auth0-js/test/user-and-pass.tests' {
  declare module.exports: any;
}

declare module 'auth0-js/version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'auth0-js/Gruntfile.js' {
  declare module.exports: $Exports<'auth0-js/Gruntfile'>;
}
declare module 'auth0-js/index' {
  declare module.exports: $Exports<'auth0-js'>;
}
declare module 'auth0-js/index.js' {
  declare module.exports: $Exports<'auth0-js'>;
}
declare module 'auth0-js/lib/assert_required.js' {
  declare module.exports: $Exports<'auth0-js/lib/assert_required'>;
}
declare module 'auth0-js/lib/base64_url.js' {
  declare module.exports: $Exports<'auth0-js/lib/base64_url'>;
}
declare module 'auth0-js/lib/IframeHandler.js' {
  declare module.exports: $Exports<'auth0-js/lib/IframeHandler'>;
}
declare module 'auth0-js/lib/index-of.js' {
  declare module.exports: $Exports<'auth0-js/lib/index-of'>;
}
declare module 'auth0-js/lib/is-array.js' {
  declare module.exports: $Exports<'auth0-js/lib/is-array'>;
}
declare module 'auth0-js/lib/json-parse.js' {
  declare module.exports: $Exports<'auth0-js/lib/json-parse'>;
}
declare module 'auth0-js/lib/LoginError.js' {
  declare module.exports: $Exports<'auth0-js/lib/LoginError'>;
}
declare module 'auth0-js/lib/nonce-generator.js' {
  declare module.exports: $Exports<'auth0-js/lib/nonce-generator'>;
}
declare module 'auth0-js/lib/same-origin.js' {
  declare module.exports: $Exports<'auth0-js/lib/same-origin'>;
}
declare module 'auth0-js/lib/SilentAuthenticationHandler.js' {
  declare module.exports: $Exports<'auth0-js/lib/SilentAuthenticationHandler'>;
}
declare module 'auth0-js/lib/use_jsonp.js' {
  declare module.exports: $Exports<'auth0-js/lib/use_jsonp'>;
}
declare module 'auth0-js/standalone.js' {
  declare module.exports: $Exports<'auth0-js/standalone'>;
}
declare module 'auth0-js/test/iframe-handler.test.js' {
  declare module.exports: $Exports<'auth0-js/test/iframe-handler.test'>;
}
declare module 'auth0-js/test/index.tests.js' {
  declare module.exports: $Exports<'auth0-js/test/index.tests'>;
}
declare module 'auth0-js/test/logout.tests.js' {
  declare module.exports: $Exports<'auth0-js/test/logout.tests'>;
}
declare module 'auth0-js/test/passwordless.tests.js' {
  declare module.exports: $Exports<'auth0-js/test/passwordless.tests'>;
}
declare module 'auth0-js/test/support/config.js' {
  declare module.exports: $Exports<'auth0-js/test/support/config'>;
}
declare module 'auth0-js/test/user-and-pass.tests.js' {
  declare module.exports: $Exports<'auth0-js/test/user-and-pass.tests'>;
}
declare module 'auth0-js/version.js' {
  declare module.exports: $Exports<'auth0-js/version'>;
}
