// flow-typed signature: 904bdcb7152a8f9d6609da0c87a406a8
// flow-typed version: <<STUB>>/exists-async_v^2.0.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'exists-async'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'exists-async' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'exists-async/index' {
  declare module.exports: $Exports<'exists-async'>;
}
declare module 'exists-async/index.js' {
  declare module.exports: $Exports<'exists-async'>;
}
