// flow-typed signature: 65cda44917dde3a34d0200388a0765a3
// flow-typed version: <<STUB>>/gulp-sourcemaps_v^1.6.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-sourcemaps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-sourcemaps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-sourcemaps/src/init' {
  declare module.exports: any;
}

declare module 'gulp-sourcemaps/src/utils' {
  declare module.exports: any;
}

declare module 'gulp-sourcemaps/src/write' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-sourcemaps/index' {
  declare module.exports: $Exports<'gulp-sourcemaps'>;
}
declare module 'gulp-sourcemaps/index.js' {
  declare module.exports: $Exports<'gulp-sourcemaps'>;
}
declare module 'gulp-sourcemaps/src/init.js' {
  declare module.exports: $Exports<'gulp-sourcemaps/src/init'>;
}
declare module 'gulp-sourcemaps/src/utils.js' {
  declare module.exports: $Exports<'gulp-sourcemaps/src/utils'>;
}
declare module 'gulp-sourcemaps/src/write.js' {
  declare module.exports: $Exports<'gulp-sourcemaps/src/write'>;
}
