// flow-typed signature: 9fd1a527cd6472fe93081f8d28c17456
// flow-typed version: <<STUB>>/gulp_vgit+https://github.com/gulpjs/gulp#4.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp/bin/gulp' {
  declare module.exports: any;
}

declare module 'gulp/test/dest' {
  declare module.exports: any;
}

declare module 'gulp/test/src' {
  declare module.exports: any;
}

declare module 'gulp/test/watch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp/bin/gulp.js' {
  declare module.exports: $Exports<'gulp/bin/gulp'>;
}
declare module 'gulp/index' {
  declare module.exports: $Exports<'gulp'>;
}
declare module 'gulp/index.js' {
  declare module.exports: $Exports<'gulp'>;
}
declare module 'gulp/test/dest.js' {
  declare module.exports: $Exports<'gulp/test/dest'>;
}
declare module 'gulp/test/src.js' {
  declare module.exports: $Exports<'gulp/test/src'>;
}
declare module 'gulp/test/watch.js' {
  declare module.exports: $Exports<'gulp/test/watch'>;
}
