// flow-typed signature: cb460130be45f40ec0e4b0f2b0560f62
// flow-typed version: <<STUB>>/gulp-cli_v^1.2.2/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-cli/bin/gulp' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/shared/cliOptions' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/shared/completion' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/shared/exit' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/shared/getBlacklist' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/shared/log/blacklistError' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/shared/log/tasks' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/shared/log/toConsole' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/shared/log/verify' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/shared/registerExports' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/shared/verifyDependencies' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/versioned/^3.7.0/formatError' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/versioned/^3.7.0/index' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/versioned/^3.7.0/log/events' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/versioned/^3.7.0/log/tasksSimple' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/versioned/^3.7.0/taskTree' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/versioned/^4.0.0-alpha.1/index' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/versioned/^4.0.0-alpha.2/index' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/versioned/^4.0.0/formatError' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/versioned/^4.0.0/index' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/versioned/^4.0.0/log/events' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/versioned/^4.0.0/log/getTask' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/versioned/^4.0.0/log/syncTask' {
  declare module.exports: any;
}

declare module 'gulp-cli/lib/versioned/^4.0.0/log/tasksSimple' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-cli/bin/gulp.js' {
  declare module.exports: $Exports<'gulp-cli/bin/gulp'>;
}
declare module 'gulp-cli/index' {
  declare module.exports: $Exports<'gulp-cli'>;
}
declare module 'gulp-cli/index.js' {
  declare module.exports: $Exports<'gulp-cli'>;
}
declare module 'gulp-cli/lib/shared/cliOptions.js' {
  declare module.exports: $Exports<'gulp-cli/lib/shared/cliOptions'>;
}
declare module 'gulp-cli/lib/shared/completion.js' {
  declare module.exports: $Exports<'gulp-cli/lib/shared/completion'>;
}
declare module 'gulp-cli/lib/shared/exit.js' {
  declare module.exports: $Exports<'gulp-cli/lib/shared/exit'>;
}
declare module 'gulp-cli/lib/shared/getBlacklist.js' {
  declare module.exports: $Exports<'gulp-cli/lib/shared/getBlacklist'>;
}
declare module 'gulp-cli/lib/shared/log/blacklistError.js' {
  declare module.exports: $Exports<'gulp-cli/lib/shared/log/blacklistError'>;
}
declare module 'gulp-cli/lib/shared/log/tasks.js' {
  declare module.exports: $Exports<'gulp-cli/lib/shared/log/tasks'>;
}
declare module 'gulp-cli/lib/shared/log/toConsole.js' {
  declare module.exports: $Exports<'gulp-cli/lib/shared/log/toConsole'>;
}
declare module 'gulp-cli/lib/shared/log/verify.js' {
  declare module.exports: $Exports<'gulp-cli/lib/shared/log/verify'>;
}
declare module 'gulp-cli/lib/shared/registerExports.js' {
  declare module.exports: $Exports<'gulp-cli/lib/shared/registerExports'>;
}
declare module 'gulp-cli/lib/shared/verifyDependencies.js' {
  declare module.exports: $Exports<'gulp-cli/lib/shared/verifyDependencies'>;
}
declare module 'gulp-cli/lib/versioned/^3.7.0/formatError.js' {
  declare module.exports: $Exports<'gulp-cli/lib/versioned/^3.7.0/formatError'>;
}
declare module 'gulp-cli/lib/versioned/^3.7.0/index.js' {
  declare module.exports: $Exports<'gulp-cli/lib/versioned/^3.7.0/index'>;
}
declare module 'gulp-cli/lib/versioned/^3.7.0/log/events.js' {
  declare module.exports: $Exports<'gulp-cli/lib/versioned/^3.7.0/log/events'>;
}
declare module 'gulp-cli/lib/versioned/^3.7.0/log/tasksSimple.js' {
  declare module.exports: $Exports<'gulp-cli/lib/versioned/^3.7.0/log/tasksSimple'>;
}
declare module 'gulp-cli/lib/versioned/^3.7.0/taskTree.js' {
  declare module.exports: $Exports<'gulp-cli/lib/versioned/^3.7.0/taskTree'>;
}
declare module 'gulp-cli/lib/versioned/^4.0.0-alpha.1/index.js' {
  declare module.exports: $Exports<'gulp-cli/lib/versioned/^4.0.0-alpha.1/index'>;
}
declare module 'gulp-cli/lib/versioned/^4.0.0-alpha.2/index.js' {
  declare module.exports: $Exports<'gulp-cli/lib/versioned/^4.0.0-alpha.2/index'>;
}
declare module 'gulp-cli/lib/versioned/^4.0.0/formatError.js' {
  declare module.exports: $Exports<'gulp-cli/lib/versioned/^4.0.0/formatError'>;
}
declare module 'gulp-cli/lib/versioned/^4.0.0/index.js' {
  declare module.exports: $Exports<'gulp-cli/lib/versioned/^4.0.0/index'>;
}
declare module 'gulp-cli/lib/versioned/^4.0.0/log/events.js' {
  declare module.exports: $Exports<'gulp-cli/lib/versioned/^4.0.0/log/events'>;
}
declare module 'gulp-cli/lib/versioned/^4.0.0/log/getTask.js' {
  declare module.exports: $Exports<'gulp-cli/lib/versioned/^4.0.0/log/getTask'>;
}
declare module 'gulp-cli/lib/versioned/^4.0.0/log/syncTask.js' {
  declare module.exports: $Exports<'gulp-cli/lib/versioned/^4.0.0/log/syncTask'>;
}
declare module 'gulp-cli/lib/versioned/^4.0.0/log/tasksSimple.js' {
  declare module.exports: $Exports<'gulp-cli/lib/versioned/^4.0.0/log/tasksSimple'>;
}
