// flow-typed signature: 4984dc995de93bd29b1beaf9d8679193
// flow-typed version: <<STUB>>/hasbin_v^1.2.3/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hasbin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'hasbin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hasbin/lib/hasbin' {
  declare module.exports: any;
}

declare module 'hasbin/test/unit/lib/hasbin' {
  declare module.exports: any;
}

declare module 'hasbin/test/unit/mock/fs' {
  declare module.exports: any;
}

declare module 'hasbin/test/unit/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hasbin/lib/hasbin.js' {
  declare module.exports: $Exports<'hasbin/lib/hasbin'>;
}
declare module 'hasbin/test/unit/lib/hasbin.js' {
  declare module.exports: $Exports<'hasbin/test/unit/lib/hasbin'>;
}
declare module 'hasbin/test/unit/mock/fs.js' {
  declare module.exports: $Exports<'hasbin/test/unit/mock/fs'>;
}
declare module 'hasbin/test/unit/setup.js' {
  declare module.exports: $Exports<'hasbin/test/unit/setup'>;
}
