// flow-typed signature: 6ff3f9327aea1e7e79d4967cafb49b1f
// flow-typed version: <<STUB>>/home-dir_v^1.0.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'home-dir'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'home-dir' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'home-dir/index' {
  declare module.exports: $Exports<'home-dir'>;
}
declare module 'home-dir/index.js' {
  declare module.exports: $Exports<'home-dir'>;
}
