// flow-typed signature: 6cd1dcf26c804636268c83b0468ee5ed
// flow-typed version: <<STUB>>/instapromise_v2.0.7-rc.1/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'instapromise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'instapromise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'instapromise/build/instapromise' {
  declare module.exports: any;
}

declare module 'instapromise/build/promisify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'instapromise/build/instapromise.js' {
  declare module.exports: $Exports<'instapromise/build/instapromise'>;
}
declare module 'instapromise/build/promisify.js' {
  declare module.exports: $Exports<'instapromise/build/promisify'>;
}
