// flow-typed signature: da3306d5807ea8a6a70667b6272f2e89
// flow-typed version: <<STUB>>/jsonfile_v^2.3.1/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsonfile'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsonfile' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'jsonfile/index' {
  declare module.exports: $Exports<'jsonfile'>;
}
declare module 'jsonfile/index.js' {
  declare module.exports: $Exports<'jsonfile'>;
}
