// flow-typed signature: 99829d786ab1b262fcb15a9a2b9723f1
// flow-typed version: <<STUB>>/ngrok_vgit+https://github.com/exponent/ngrok#v1.3.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ngrok'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'ngrok' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ngrok/postinstall' {
  declare module.exports: any;
}

declare module 'ngrok/test/chai' {
  declare module.exports: any;
}

declare module 'ngrok/test/ngrok.authtoken.spec' {
  declare module.exports: any;
}

declare module 'ngrok/test/ngrok.guest.eventemitter.spec' {
  declare module.exports: any;
}

declare module 'ngrok/test/ngrok.guest.spec' {
  declare module.exports: any;
}

declare module 'ngrok/test/ngrok.registered.free.spec' {
  declare module.exports: any;
}

declare module 'ngrok/test/ngrok.registered.paid.spec' {
  declare module.exports: any;
}

declare module 'ngrok/test/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ngrok/index' {
  declare module.exports: $Exports<'ngrok'>;
}
declare module 'ngrok/index.js' {
  declare module.exports: $Exports<'ngrok'>;
}
declare module 'ngrok/postinstall.js' {
  declare module.exports: $Exports<'ngrok/postinstall'>;
}
declare module 'ngrok/test/chai.js' {
  declare module.exports: $Exports<'ngrok/test/chai'>;
}
declare module 'ngrok/test/ngrok.authtoken.spec.js' {
  declare module.exports: $Exports<'ngrok/test/ngrok.authtoken.spec'>;
}
declare module 'ngrok/test/ngrok.guest.eventemitter.spec.js' {
  declare module.exports: $Exports<'ngrok/test/ngrok.guest.eventemitter.spec'>;
}
declare module 'ngrok/test/ngrok.guest.spec.js' {
  declare module.exports: $Exports<'ngrok/test/ngrok.guest.spec'>;
}
declare module 'ngrok/test/ngrok.registered.free.spec.js' {
  declare module.exports: $Exports<'ngrok/test/ngrok.registered.free.spec'>;
}
declare module 'ngrok/test/ngrok.registered.paid.spec.js' {
  declare module.exports: $Exports<'ngrok/test/ngrok.registered.paid.spec'>;
}
declare module 'ngrok/test/util.js' {
  declare module.exports: $Exports<'ngrok/test/util'>;
}
