// flow-typed signature: 65dc6ce32889be213d858768cfa6893b
// flow-typed version: <<STUB>>/slugify_v^1.0.2/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'slugify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'slugify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'slugify/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'slugify/lib/index.js' {
  declare module.exports: $Exports<'slugify/lib/index'>;
}
