// flow-typed signature: 3002e30f9b7d3bcb4c7a2740db5326dd
// flow-typed version: <<STUB>>/slugid_v^1.1.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'slugid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'slugid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'slugid/slugid_test' {
  declare module.exports: any;
}

declare module 'slugid/slugid' {
  declare module.exports: any;
}

// Filename aliases
declare module 'slugid/index' {
  declare module.exports: $Exports<'slugid'>;
}
declare module 'slugid/index.js' {
  declare module.exports: $Exports<'slugid'>;
}
declare module 'slugid/slugid_test.js' {
  declare module.exports: $Exports<'slugid/slugid_test'>;
}
declare module 'slugid/slugid.js' {
  declare module.exports: $Exports<'slugid/slugid'>;
}
