// flow-typed signature: 43111a350cdd0e282eda263014ff1b55
// flow-typed version: <<STUB>>/tree-kill_v^1.1.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tree-kill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'tree-kill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tree-kill/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tree-kill/cli.js' {
  declare module.exports: $Exports<'tree-kill/cli'>;
}
declare module 'tree-kill/index' {
  declare module.exports: $Exports<'tree-kill'>;
}
declare module 'tree-kill/index.js' {
  declare module.exports: $Exports<'tree-kill'>;
}
