// flow-typed signature: acbceb780f11fe8cc44218209ec181c1
// flow-typed version: <<STUB>>/unzip_v^0.1.11/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'unzip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'unzip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'unzip/lib/entry' {
  declare module.exports: any;
}

declare module 'unzip/lib/extract' {
  declare module.exports: any;
}

declare module 'unzip/lib/parse' {
  declare module.exports: any;
}

declare module 'unzip/test/compressed' {
  declare module.exports: any;
}

declare module 'unzip/test/fileSizeUnknownFlag' {
  declare module.exports: any;
}

declare module 'unzip/test/pipeSingleEntry' {
  declare module.exports: any;
}

declare module 'unzip/test/uncompressed' {
  declare module.exports: any;
}

declare module 'unzip/unzip' {
  declare module.exports: any;
}

// Filename aliases
declare module 'unzip/lib/entry.js' {
  declare module.exports: $Exports<'unzip/lib/entry'>;
}
declare module 'unzip/lib/extract.js' {
  declare module.exports: $Exports<'unzip/lib/extract'>;
}
declare module 'unzip/lib/parse.js' {
  declare module.exports: $Exports<'unzip/lib/parse'>;
}
declare module 'unzip/test/compressed.js' {
  declare module.exports: $Exports<'unzip/test/compressed'>;
}
declare module 'unzip/test/fileSizeUnknownFlag.js' {
  declare module.exports: $Exports<'unzip/test/fileSizeUnknownFlag'>;
}
declare module 'unzip/test/pipeSingleEntry.js' {
  declare module.exports: $Exports<'unzip/test/pipeSingleEntry'>;
}
declare module 'unzip/test/uncompressed.js' {
  declare module.exports: $Exports<'unzip/test/uncompressed'>;
}
declare module 'unzip/unzip.js' {
  declare module.exports: $Exports<'unzip/unzip'>;
}
