export default {
  START_LOADING: 'START_LOADING',
  STOP_LOADING: 'STOP_LOADING',
  START_PROGRESS_BAR: 'START_PROGRESS_BAR',
  TICK_PROGRESS_BAR: 'TICK_PROGRESS_BAR',
  STOP_PROGRESS_BAR: 'STOP_PROGRESS_BAR',
};
