import { install as installSourceMapSupport } from 'source-map-support';

import Analytics from './Analytics';
import * as Android from './Android';
import Api from './Api';
import ApiV2 from './ApiV2';
import * as Binaries from './Binaries';
import Config from './Config';
import * as ConnectionStatus from './ConnectionStatus';
import * as Exp from './Exp';
import Logger from './Logger';
import NotificationCode from './NotificationCode';
import * as Project from './Project';
import * as ProjectSettings from './ProjectSettings';
import * as Prompts from './Prompts';
import * as SimControl from './SimControl';
import * as Simulator from './Simulator';
import * as StandaloneBuild from './StandaloneBuild';
import * as ThirdParty from './ThirdParty';
import * as UrlUtils from './UrlUtils';
import UserManager, { RobotUser, User } from './User';
import UserSettings from './UserSettings';
import * as Versions from './Versions';
import * as Webpack from './Webpack';
import XDLError from './XDLError';
import * as AndroidCredentials from './credentials/AndroidCredentials';
import * as PKCS12Utils from './detach/PKCS12Utils';
import PackagerLogsStream, { LogRecord, LogUpdater } from './logs/PackagerLogsStream';
import * as Doctor from './project/Doctor';
import * as ProjectUtils from './project/ProjectUtils';
import * as ModuleVersion from './tools/ModuleVersion';

const Detach: any = require('./detach/Detach.js');
const IosCodeSigning = require('./detach/IosCodeSigning.js');

if (process.env.NODE_ENV !== 'production' && process.env.NODE_ENV !== 'test') {
  installSourceMapSupport();
}
export { Analytics };
export { Android };
export { Api };
export { ApiV2 };
export { Binaries };
export { Config };
export { AndroidCredentials };
export { ConnectionStatus };
export { Detach };
export { Doctor };
export { Exp };
export { StandaloneBuild };
export { IosCodeSigning };
export { Logger };
export { ModuleVersion };
export { NotificationCode };
export { PackagerLogsStream, LogRecord, LogUpdater };
export { PKCS12Utils };
export { Project };
export { Prompts };
export { ProjectSettings };
export { ProjectUtils };
export { SimControl };
export { Simulator };
export { ThirdParty };
export { UrlUtils };
export { UserManager, User, RobotUser };
export { UserSettings };
export { Versions };
export { Webpack };
export { XDLError };
